src/KonigDev.Lazurit.Store/Controllers/AdministrativeToolsController.cs
using KonigDev.Lazurit.Store.Extensions.Filters;
using System.Web.Mvc;
using AuthDTOConstants = KonigDev.Lazurit.Auth.Model.DTO.Constants;

namespace KonigDev.Lazurit.Store.Controllers
{
    [Authorize]
    [NotImplExceptionFilter]
    public class AdministrativeToolsController : Controller
    {
        /// <summary>
        /// Страница просмотра заказов
        /// </summary>
        /// <returns></returns>
        [Authorize(Roles = AuthDTOConstants.AdminRoleName + "," + AuthDTOConstants.ShopSallerRoleName)]
        public ActionResult OrdersTool()
        {
            return View();
        }

        /// <summary>
        /// Страница верификации продавцов
        /// </summary>
        /// <returns></returns>
        [Authorize(Roles = AuthDTOConstants.AdminRoleName)]
        public ActionResult VerifySellers()
        {
            return View();
        }

        /// <summary>
        /// Страница управления продавцами
        /// </summary>
        /// <returns></returns>
        [Authorize(Roles = AuthDTOConstants.AdminRoleName)]
        public ActionResult Sellers()
        {
            return View();
        }
        /// <summary>
        /// Страница управления административными ролями
        /// </summary>
        /// <returns></returns>
        [Authorize(Roles = AuthDTOConstants.AdminRoleName)]
        public ActionResult AdministrativeRoles()
        {
            return View();
        }

        /// <summary>
        /// Управление пользователями-клиентами
        /// </summary>
        /// <returns></returns>
        [Authorize(Roles = AuthDTOConstants.AdminRoleName)]
        public ActionResult AllocateRole()
        {
            return View();
        }

        /// <summary>
        /// Управление маркетинговыми акциями
        /// </summary>
        /// <returns></returns>
        [Authorize(Roles = AuthDTOConstants.AdminRoleName)]
        public ActionResult MarketingActions()
        {
            return View();
        }

        /// <summary>
        /// List of customer requests
        /// </summary>
        /// <remarks>
        /// List of call request, designer request, etc.
        /// </remarks>
        [Authorize(Roles = AuthDTOConstants.AdminRoleName + "," + AuthDTOConstants.MarketerRoleName)]
        public ActionResult CustomerRequests()
        {
            return View();
        }
    }
}

src/KonigDev.Lazurit.Store/Controllers/CatalogController.cs
using AutoMapper;
using KonigDev.Lazurit.Core.Enums;
using KonigDev.Lazurit.Hub.Grains.Interfaces;
using KonigDev.Lazurit.Hub.Model.DTO.Article;
using KonigDev.Lazurit.Hub.Model.DTO.Article.Query;
using KonigDev.Lazurit.Hub.Model.DTO.Collections;
using KonigDev.Lazurit.Hub.Model.DTO.Collections.Query;
using KonigDev.Lazurit.Hub.Model.DTO.FilesContent.Dto;
using KonigDev.Lazurit.Hub.Model.DTO.FilesContent.Queries;
using KonigDev.Lazurit.Hub.Model.DTO.FurnitureTypes.Dto;
using KonigDev.Lazurit.Hub.Model.DTO.FurnitureTypes.Query;
using KonigDev.Lazurit.Hub.Model.DTO.Products.Dto;
using KonigDev.Lazurit.Hub.Model.DTO.Products.Query;
using KonigDev.Lazurit.Hub.Model.DTO.RoomTypes;
using KonigDev.Lazurit.Hub.Model.DTO.RoomTypes.Query;
using KonigDev.Lazurit.Store.Dto.Article;
using KonigDev.Lazurit.Store.Dto.Catalog;
using KonigDev.Lazurit.Store.Dto.Collection;
using KonigDev.Lazurit.Store.Dto.Prices;
using KonigDev.Lazurit.Store.Extensions;
using KonigDev.Lazurit.Store.Extensions.Filters;
using KonigDev.Lazurit.Store.Services.LazuritContext;
using KonigDev.Lazurit.Store.Services.PriceSrvice;
using Microsoft.AspNet.Identity;
using MoreLinq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using KonigDev.Lazurit.Store.Dto.Product;

namespace KonigDev.Lazurit.Store.Controllers
{
    [NotImplExceptionFilter]
    public class CatalogController : Controller
    {
        private readonly IHubHandlersFactory _hubFactory;
        private readonly IPriceService _priceService;
        private readonly ILazuritCtxSessionService _lazuritCtxService;

        public CatalogController(IHubHandlersFactory hubFactory, ILazuritCtxSessionService lazuritCtxService, IPriceService priceService)
        {
            _hubFactory = hubFactory;
            _priceService = priceService;
            _lazuritCtxService = lazuritCtxService;
        }

        [HttpGet]
        public ActionResult Index()
        {
            var getCatalogQueryHandler = _hubFactory.CreateQueryHandler<GetRoomTypesQuery, List<DtoRoomTypesResult>>();
            var rooms = getCatalogQueryHandler.Execute(new GetRoomTypesQuery()).Result;

            /* todo откидываем те записи, у которыех нет вариантов коллекции, посмотреть перенос логики в грейн?
             * необходимо чтобы не отображались комнаты, с коллекциями, у кторых нет опубликованных вариантов */
            foreach (var item in rooms)
                item.Collections = item.Collections.Where(p => p.DefaultVariantId != Guid.Empty).ToList();
            rooms = rooms.Where(p => p.Collections.Any()).ToList();

            //distincting all filters for specific room type 
            foreach (var room in rooms)
            {
                room.Styles = room.Collections.SelectMany(c => c.Styles).DistinctBy(s => s.Id);
                room.TargetAudiences = room.Collections.SelectMany(c => c.TargetAudiences).DistinctBy(ta => ta.Id);
            }
            //distincting all filters for all room types
            var roomsExtended = new DtoRoomsExtendedResult
            {
                Rooms = rooms,
                Styles = rooms.SelectMany(r => r.Styles).DistinctBy(s => s.Id),
                TargetAudiences = rooms.SelectMany(r => r.TargetAudiences).DistinctBy(ta => ta.Id)
            };
            return View(roomsExtended);
        }

        [HttpGet]
        public ActionResult Room(string alias)
        {
            return View(new DTORomByAliasResult() { Alias = alias });
        }

        [HttpGet]
        public ActionResult Collection(string roomAlias, string collectionAlias)
        {
            return View(new DTOCollectionFoomResult
            {
                RommAlias = roomAlias,
                CollectionAlias = collectionAlias
            });
        }

        //GET : PRODUCT
        //[SiteMapTitle("alias")]
        public async Task<ActionResult> Product(string furnitureAlias, string productAlias)
        {
            /* todo вынести все это в отдельный сервис/класс - тут слишком много всего, нечитаемо */
            var parserResult = ProductAliasParser.ParseAlias(productAlias);
            if (parserResult.HasErrors)
                return HttpNotFound();

            var getArticleQueryHandler = _hubFactory.CreateQueryHandler<GetArticleByUniqueFieldsQuery, DtoArticleByUniqueFieldsQueryResult>();
            var article = await getArticleQueryHandler.Execute(new GetArticleByUniqueFieldsQuery
            {
                ArticleSyncCode1C = parserResult.ArticleCodeOnlyDigits
            });
            if (article == null)
                return HttpNotFound();
            // не используется. удалить закоменченное после того, как убедимся, что не нужно
            //var getCollectionByAlias = _hubFactory.CreateQueryHandler<GetCollectionByAliasQuery, DtoCollectionByAliasResult>();
            //var collection = await getCollectionByAlias.Execute(new GetCollectionByAliasQuery
            //{
            //    Alias = parserResult.CollectionAlias
            //});

            var result = new DtoArticleWithFilesContent
            {
                Article = article,
                ProductsfilesContent = new List<DtoProductFilesContent>()
                // Collection = collection
            };

            var handler = _hubFactory.CreateQueryHandler<GetFilesContentByRequestQuery, List<DtoFilesContent>>();
            foreach (var product in result.Article.Products)
            {
                var fileContentResult = await handler.Execute(new GetFilesContentByRequestQuery
                {
                    ObjectId = product.Id,
                    Type = EnumFileContentType.None
                });
                result.ProductsfilesContent.Add(new DtoProductFilesContent
                {
                    ProductId = product.Id,
                    ProductFilesContent = fileContentResult
                });
            }
            return View(result);
        }

        public async Task<ActionResult> GetProductsFromSameCollection(GetProductsByRequestQuery query)
        {
            if (query == null)
                return PartialView(new List<DtoProduct>());

            var handler = _hubFactory.CreateQueryHandler<GetProductsByRequestQuery, List<DtoProduct>>();
            query.UserId = User.Identity.IsAuthenticated ? Guid.Parse(User.Identity.GetUserId()) : (Guid?)null;
            var dto = await handler.Execute(query);

            //TODO использовать через ninject (IMapperEngine или что-то в этом духе у него уже есть.)
            var model = Mapper.Map<List<DtoProductPrice>>(dto);

            var priceInfo = _lazuritCtxService.GetPriceInfoFromContext();
            await _priceService.GetProductsPrices(priceInfo.PriceZoneId, priceInfo.Currency, model);
            return PartialView(model);
        }

        public async Task<ActionResult> Furniture()
        {
            var getFurnitureTypesWithDefaultProductQuery = _hubFactory.CreateQueryHandler<GetFurnitureTypesWithDefaultProductQuery, List<DtoFurnitureTypeWithDefaultProductResult>>();
            var data = await getFurnitureTypesWithDefaultProductQuery.Execute(new GetFurnitureTypesWithDefaultProductQuery());

            return View(data);
        }

        public ActionResult ProductsInFurniture(string furnitureAlias)
        {
            return View(new DtoProductsByFurnitureAlias { FurnitureAlias = furnitureAlias });
        }

        public ActionResult ProductsInSubFurniture(string parentFurnitureAlias, string furnitureAlias)
        {
            if (parentFurnitureAlias == furnitureAlias)
                return RedirectToAction("ProductsInFurniture", new { furnitureAlias });
            return View(new DtoProductsByFurnitureAlias { ParentFurnitureAlias = parentFurnitureAlias, FurnitureAlias = furnitureAlias });
        }
    }
}

src/KonigDev.Lazurit.Store/Views/Shared/CityPartial.cshtml
@using KonigDev.Lazurit.Hub.Model.DTO.Cities.Queries;
@using System.Linq;
@model List<DtoCity>

@{ 
    var cityName = "";
    foreach(var city in Model)
    {
        if (city.IsNearest == true)
        {
            cityName = city.Title;
        }
    }
}
<div ng-cloak>
    <div style="background-color: powderblue; margin-left: 75%;>
        <div ng-show="geoCtrl.isShowCityPopup">
            <div>Ваш город: @cityName?</div>
            <button ng-click="geoCtrl.asseptCity('@cityName')">Да</button>
            <button ng-click="geoCtrl.rejectCity()">Нет</button>
        </div>

        <div ng-show="geoCtrl.isShowCitiesPopup" class="ng-cloak">
            <div>Выберите город</div>
            @foreach (var city in Model)
            {
                <br />
                <a href="javascript:void(0)" ng-click="geoCtrl.selectCity('@city.Id', '@city.Title', '@city.PriceZoneId', '@city.DeliveryPrice')">@city.Title</a>
            }
        </div>
    </div>
</div>

src/KonigDev.Lazurit.Store/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en" class="@ViewBag.PageClass">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Lazurit</title>    
    <link rel="stylesheet" type="text/css" href="/wwwroot/style.css" />
    @Html.MvcSiteMap().CanonicalTag()
    @Html.MvcSiteMap().MetaRobotsTag()
    <link type="text/css" rel="stylesheet" href="~/Content/src/mr-image/mr-image.min.css" />
    <!--<link rel="stylesheet" type="text/css" href="~/wwwroot/lib/chosenjq/chosen.css" />-->
    <link href="/wwwroot/lib/jquerykladr/jquery.kladr.min.css" rel="stylesheet" />
    <link href="~/wwwroot/lib/angular-toastr/angular-toastr.css" rel="stylesheet"/>
    <style>
        .item.tooltip:hover {
            opacity: 1;
        }
        .tooltip>.item-add:hover {
               opacity: 1;
        }
    </style>
    @RenderSection("styles", required: false)
    <link rel="shortcut icon" href="~/Content/favicon/favicon.ico" type="image/x-icon">
</head>
<body ng-app="KonigDevApp" ng-strict-di="true">
    <!-- Header -->
    <header class="header auto-hide-header">
        <div class="header-inner">
            <!--Logo-->
            <div class="header-logo">
                <a href="/"><img src="~/Content/src/img/logo.svg" alt="Интернет магазнин мебели Лазурит" /></a>
            </div>
            <!--Navigation-->
            <nav class="header-navigation">
                <ul class="header-navigation_container">
                    <li class="header-navigation_container--item nav-link_home">
                        <a href="@Url.Action("", "Home")">Главная</a>
                    </li>
                    <li class="header-navigation_container--item nav-link_catalog">
                        <a href="@Url.Action("", "Catalog")">Каталог</a> <!-- todo установить тут урл из сайтмапа!!! -->
                        <ul>
                            <li><a ng-href="/catalog">Комнаты</a></li>
                            <li><a ng-href="/catalog-single">Предметы мебели</a></li>

                        </ul>
                    </li>
                    <li class="header-navigation_container--item nav-link_stock">
                        <a href="javascript:void(0)">Акции</a>
                    </li>
                    <li class="header-navigation_container--item nav-link_contacts">
                        <a href="javascript:void(0)">Контакты</a>
                    </li>
                </ul>
            </nav>
            <div class="header-tools">
                @{
                    string isAuth = "false";
                    if (Html.ViewContext.HttpContext.User != null && Html.ViewContext.HttpContext.User.Identity != null)
                    {
                        isAuth = Html.ViewContext.HttpContext.User.Identity.IsAuthenticated.ToString().ToLower();
                    }
                }
                <kd-header-tools phone-number="'8 800 100-50-22'" is-authenticated="@isAuth" return-url="@ViewBag.ReurnUrl"></kd-header-tools>
            </div>
        </div>
    </header>
    <!-- Body -->
    @RenderBody()
    <cart-mini-component></cart-mini-component>
    <!-- Footer -->
    @*<footer class="container-fluid footer text-center">
            <p>This project is made by Keniglabs team @DateTime.Now.Year</p>
        </footer>*@
    <script src="/wwwroot/lib/jquery/jquery.min.js"></script>
    <script src="/wwwroot/vendor.js"></script>
    <script src="/wwwroot/lib/chosenjq/chosen.jquery.js"></script>
    <script src="/wwwroot/lib/jquerykladr/jquery.kladr.min.js"></script>
    <script src="/wwwroot/lib/angular/angular.js"></script>
    <script src="/wwwroot/lib/angular-ui-router/angular-ui-router.js"></script>
    <script src="/wwwroot/lib/angular-ui-bootstrap/ui-bootstrap.js"></script>
    <script src="/wwwroot/lib/angular-ui-bootstrap/ui-bootstrap-tpls.js"></script>
    <script src="/wwwroot/lib/angular-toastr/angular-toastr.tpls.js"></script>
    <script src="/wwwroot/lib/ui-router-extras/ct-ui-router-extras.js"></script>
    <script src="/wwwroot/lib/ng-infinite-scroll/ng-infinite-scroll.min.js"></script>
    <script src="/wwwroot/lib/chosen/angular-chosen.min.js"></script>
    <script src="/wwwroot/lib/ng-infinite-scroll/ng-infinite-scroll.min.js"></script>
    <script src="/wwwroot/lib/angular-ui-mask/mask.min.js"></script>
    <script src="/Content/Scripts/clickoutside.directive.js"></script>

    <script src="/wwwroot/lib/jquerykladr/jquery.kladr.min.js"></script>
    <script src="/wwwroot/app.js"></script>
    <script src="~/content/Scripts/lazurit-slider-jq.js"></script>
    <script src="~/Content/src/mr-image/mr-image.min.js"></script>
    <script src="~/Scripts/jquery.signalR-2.1.2.min.js"></script>
    <script src="~/signalr/hubs"></script>
    <script src="~/Scripts/signalr_service.js"></script>
    <!--Скрипты артура-->
    <!--слайдер прокрутки-->
    <script type="text/javascript" src="~/Content/src/components/catalog-slider/bond.js"></script>
    <!-- Фоновое слайдшоу -->
    <script type="text/javascript" src="~/Content/src/components/background-slider/background-slider.js"></script>
    <!-- Поиск для списка городов -->
    <!-- <script type="text/javascript" src="~/Content/src/blocks/geo-list/list.min.js"></script>
    <script>
        var options = {
            valueNames: ['city-title']
        };
        var userList = new List('cities', options);
    </script>-->
    <!--
    <script src="~/Content/forProduct/chosen/ImageSelect.jquery.js"></script>
    <script type="text/javascript" src="~/Content/src/components/fancybox/jquery.fancybox.pack.js"></script>-->

    @RenderSection("scripts", required: false)
</body>
</html>

src/KonigDev.Lazurit.Store/Views/Shared/_LayoutBootstrap.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Lazurit</title>

    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet">
    <link href="~/Content/admin.css" rel="stylesheet" />
    <link href="~/Content/forProduct/chosen/admin-chosen.css" rel="stylesheet" />
    <link href="~/wwwroot/lib/angular-toastr/angular-toastr.css" rel="stylesheet" />
    <link href="~/wwwroot/lib/bootstrap/bootstrap.min.css" rel="stylesheet" />
    <link type="text/css" rel="stylesheet" href="~/Content/src/mr-image/mr-image.min.css" />
    <!--alexasha styles-->
    <link type="text/css" rel="stylesheet" href="~/Content/temporary_styles/alexasha_styles.css" />
    <script src="https://use.fontawesome.com/3842cc86a3.js"></script>
</head>
<body ng-app="KonigDevApp" ng-strict-di="true">
    <header class="navbar" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/"><img src="/Content/src/img/logo.svg" alt="Интернет магазнин мебели Лазурит"></a>
            </div>
            <a href="/" class="btn btn-default pull-right" target="_blank">На сайт</a>
            @*<div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="#">Верхняя навигация</a></li>
                        <li><a href="#">Верхняя навигация</a></li>
                        <li><a href="#">Верхняя навигация</a></li>
                    </ul>
                    <form class="navbar-form navbar-right">
                        <input type="text" class="form-control" placeholder="Поиск...">
                    </form>
                </div>*@

        </div>
    </header>

    <div class="container-fluid">
        <div class="row">
            <div class="sidebar">
                <ul class="nav nav-sidebar">
                    @if (Html.ViewContext.HttpContext.User != null && Html.ViewContext.HttpContext.User.Identity != null)
                    {
                        var user = Html.ViewContext.HttpContext.User;
                        if (user.IsInRole(KonigDev.Lazurit.Auth.Model.DTO.Constants.AdminRoleName))
                        {
                            <li><a href="/administrativetools/sellers/">Управление ролями</a></li>
                            }
                            if (user.IsInRole(KonigDev.Lazurit.Auth.Model.DTO.Constants.AdminRoleName)
                                || user.IsInRole(KonigDev.Lazurit.Auth.Model.DTO.Constants.MarketerRoleName)
                                || user.IsInRole(KonigDev.Lazurit.Auth.Model.DTO.Constants.ContentManagerRoleName))
                        {
                            <li><a href="/import/collections">Обработка выгрузки</a></li>
                            <li><a href="/import/productspublished">Активные товары</a></li>
                            <li><a href="/import/productinstallment">Скидки</a></li>
                            <li><a href="/administrativetools/orderstool">Список заказов</a></li>
                            <li><a href="/administrativetools/customerrequests">Заявки</a></li>
                            <li><a href="/administrativetools/marketingactions">Акции</a></li>

                            @*<li><a href="@Url.Action("MarketingActions", "AdministrativeTools")">Список акций</a></li>*@
                        }
                    }
                </ul>

            </div>
            <div class="col-sm-9 col-md-10 main">
                <!-- Body -->
                @RenderBody()
            </div>
        </div>
    </div>

    <script src="/wwwroot/lib/jquery/jquery.min.js"></script>
    <script src="/wwwroot/lib/chosenjq/chosen.jquery.js"></script>
    <script src="/wwwroot/vendor.js"></script>
    <script src="/wwwroot/lib/chosenjq/chosen.jquery.js"></script>

    <script src="/wwwroot/lib/angular/angular.js"></script>

    <script src="/wwwroot/lib/chosen/angular-chosen.min.js"></script>
    <script src="/wwwroot/lib/angular-ui-router/angular-ui-router.js"></script>
    <script src="/wwwroot/lib/angular-ui-bootstrap/ui-bootstrap.js"></script>
    <script src="/wwwroot/lib/angular-ui-bootstrap/ui-bootstrap-tpls.js"></script>
    <script src="/wwwroot/lib/angular-toastr/angular-toastr.tpls.js"></script>
    <script src="/wwwroot/lib/ui-router-extras/ct-ui-router-extras.js"></script>
    <script src="/wwwroot/lib/ng-infinite-scroll/ng-infinite-scroll.min.js"></script>
    <script src="/wwwroot/lib/chosen/angular-chosen.min.js"></script>
    <script src="/wwwroot/lib/ng-infinite-scroll/ng-infinite-scroll.min.js"></script>
    <script src="/wwwroot/lib/angular-ui-mask/mask.min.js"></script>
    <script src="/Content/Scripts/clickoutside.directive.js"></script>
    <script src="~/Content/src/mr-image/mr-image.min.js"></script>
    <script src="/wwwroot/app.js"></script>


    @* Скрипт для фиксациитабличных хедеров*@

    <script src="~/Content/Scripts/fixed-table-header.js"></script>

    @RenderSection("scripts", required: false)
</body>
</html>